language:
    - c

before_install:
    - pip install --user cpp-coveralls
#    - sudo apt-get update -qq
#    - sudo apt-get install -y qt5-default qttools5-dev-tools
#    - sudo apt-get install build-essential
env:
    - QT_CI_PACKAGES=qt.qt5.5132.gcc_64,qt.qt5.5132.qtwebengine PATH="$TRAVIS_BUILD_DIR/Qt/5.13.2/gcc_64/bin:${PATH}"

script:
    - git clone https://github.com/benlau/qtci.git
    - source qtci/path.env
    - install-qt 5.13.2
    - qmake 
    - make
    - ./tests/tests
addons:
  sonarcloud:
    organization: "khuaigul"
    token: $SONAR_TOKEN

after_success:
    - coveralls --root . -E ".*external.*" -E ".*tests.*"
    - build-wrapper-linux-x86-64 --out-dir bw-output make clean all
    - sonar-scanner

cache:
    directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

notifications:
    email: false
