os: windows
language:
    - c

before_install:
    - pip install --user cpp-coveralls
 #   - wget -q https://download.qt.io/official_releases/qt/5.13/5.13.2/qt-opensource-windows-x86-5.13.2.exe
    - sudo apt-get update -qq
    - sudo apt-get install -y qt5-default qttools5-dev-tools
    - sudo apt-get install build-essential

script:
    - qmake 
    - make
    - ./tests/tests
addons:
  sonarcloud:
    organization: "khuaigul"
    token: $SONAR_TOKEN

after_success:
    - coveralls --root . -E ".*external.*" -E ".*tests.*"
    - build-wrapper-linux-x86-64 --out-dir bw-output make clean all
    - sonar-scanner

cache:
    directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

notifications:
    email: false
